package com.teo.mybatis.model;

public class Basket {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASKET.ID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASKET.ID
     *
     * @return the value of BASKET.ID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASKET.ID
     *
     * @param id the value for BASKET.ID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }
}