package com.teo.mybatis.model;

public class ItemPhoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM_PHOTO.ID
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM_PHOTO.ITEM_ID
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    private Long itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM_PHOTO.NAME
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM_PHOTO.PHOTO
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM_PHOTO.ID
     *
     * @return the value of ITEM_PHOTO.ID
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM_PHOTO.ID
     *
     * @param id the value for ITEM_PHOTO.ID
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM_PHOTO.ITEM_ID
     *
     * @return the value of ITEM_PHOTO.ITEM_ID
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    public Long getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM_PHOTO.ITEM_ID
     *
     * @param itemId the value for ITEM_PHOTO.ITEM_ID
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    public void setItemId(Long itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM_PHOTO.NAME
     *
     * @return the value of ITEM_PHOTO.NAME
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM_PHOTO.NAME
     *
     * @param name the value for ITEM_PHOTO.NAME
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM_PHOTO.PHOTO
     *
     * @return the value of ITEM_PHOTO.PHOTO
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM_PHOTO.PHOTO
     *
     * @param photo the value for ITEM_PHOTO.PHOTO
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}