package com.teo.mybatis.model;

import java.math.BigDecimal;
import java.util.Date;

public class Item {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.ID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.AMOUNT
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.CREATIONDATE
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private Date creationdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.DESCRIPTION
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.NAME
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEM.PRICE
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.ID
     *
     * @return the value of ITEM.ID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.ID
     *
     * @param id the value for ITEM.ID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.AMOUNT
     *
     * @return the value of ITEM.AMOUNT
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.AMOUNT
     *
     * @param amount the value for ITEM.AMOUNT
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.CREATIONDATE
     *
     * @return the value of ITEM.CREATIONDATE
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public Date getCreationdate() {
        return creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.CREATIONDATE
     *
     * @param creationdate the value for ITEM.CREATIONDATE
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.DESCRIPTION
     *
     * @return the value of ITEM.DESCRIPTION
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.DESCRIPTION
     *
     * @param description the value for ITEM.DESCRIPTION
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.NAME
     *
     * @return the value of ITEM.NAME
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.NAME
     *
     * @param name the value for ITEM.NAME
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEM.PRICE
     *
     * @return the value of ITEM.PRICE
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEM.PRICE
     *
     * @param price the value for ITEM.PRICE
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}