package com.teo.mybatis.model;

public class Itemphoto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMPHOTO.ID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMPHOTO.ITEMID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private Long itemid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMPHOTO.NAME
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ITEMPHOTO.PHOTO
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMPHOTO.ID
     *
     * @return the value of ITEMPHOTO.ID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMPHOTO.ID
     *
     * @param id the value for ITEMPHOTO.ID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMPHOTO.ITEMID
     *
     * @return the value of ITEMPHOTO.ITEMID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public Long getItemid() {
        return itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMPHOTO.ITEMID
     *
     * @param itemid the value for ITEMPHOTO.ITEMID
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setItemid(Long itemid) {
        this.itemid = itemid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMPHOTO.NAME
     *
     * @return the value of ITEMPHOTO.NAME
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMPHOTO.NAME
     *
     * @param name the value for ITEMPHOTO.NAME
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ITEMPHOTO.PHOTO
     *
     * @return the value of ITEMPHOTO.PHOTO
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ITEMPHOTO.PHOTO
     *
     * @param photo the value for ITEMPHOTO.PHOTO
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}