package com.teo.mybatis.dao;

import com.teo.mybatis.model.Basket;
import java.util.List;

public interface BasketMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASKET
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASKET
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    int insert(Basket record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASKET
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    List<Basket> selectAll();
}