package com.teo.mybatis.dao;

import com.teo.mybatis.model.Item;
import java.util.List;

public interface ItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    int insert(Item record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    Item selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    List<Item> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM
     *
     * @mbg.generated Sat Apr 03 16:24:28 EEST 2021
     */
    int updateByPrimaryKey(Item record);
}