package com.teo.mybatis.dao;

import com.teo.mybatis.model.ItemPhoto;
import java.util.List;

public interface ItemPhotoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_PHOTO
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_PHOTO
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    int insert(ItemPhoto record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_PHOTO
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    ItemPhoto selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_PHOTO
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    List<ItemPhoto> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ITEM_PHOTO
     *
     * @mbg.generated Fri Apr 02 16:32:40 EEST 2021
     */
    int updateByPrimaryKey(ItemPhoto record);
}